import { makeStyles } from '@material-ui/core/styles';
import { lmsStyle } from 'styles/ui.variables';

export const useStyles = makeStyles(() => ({
  dropbox: {
    border: '1px dashed grey',
    margin: '17px',
    height: '159px',
    boxShadow: `0px 3px 6px ${lmsStyle['box-shadow']}`,
    borderRadius: '5px',
    opacity: '1',
  },
  pQ: {
    fontSize: '14',
    marginTop: '20px',
    color: lmsStyle['base-secondary'],
    marginBottom: '0px',
    fontWeight: 'bold',
  },
  textcover: {
    textAlign: 'left',
    fontWeight: 'bold',
    marginTop: 0,
    marginBottom: '0px !Important',
    fontSize: 11,
    color: lmsStyle['base-gray-500'],
    verticalAlign: 'top',
  },

  editbtn: {
    color: lmsStyle['base-primary'],
    backgroundColor: 'none',
    position: 'absolute',
    right: '40px',
    textTransform: 'capitalize',
    fontWeight: 'bold',
    marginTop: '-25px',

    whiteSpace: 'nowrap',
    fontSize: '14px',
  },
  img: {
    paddingTop: '30px',
    marginTop: '10px',
    margin: '0 auto',
    display: 'flex',
  },
  OverviewCard: {
    width: '1040px',
    height: '199px',
    marginBottom: '-7px',
    boxShadow: '0px 3px 6px #00000008',
    border: `1px solid ${lmsStyle['base-gray-300']}`,
  },

  boxcolor: {
    padding: '20px',
    backgroundColor: 'white',
    overflow: 'hidden',
    height: '100%',
  },
  discription: {
    margin: 0,
    padding: 0,
    marginBottom: '0px !Important',
    fontSize: 10,
    fontWeight: 'bold',
    color: lmsStyle['base-gray-500'],
  },
  text: {
    marginBottom: '-10px !Important',
    fontSize: 10,
    fontWeight: 'bold',
    color: lmsStyle['base-gray-500'],
  },
  Editordiv: {
    border: `1px solid ${lmsStyle['base-gray-300']}`,
    borderRadius: '5px',
    width: '1040px',
    height: '205px',
  },
  pDrag: {
    margin: '0 auto',
    display: 'flex',
    fontSize: '10px',
    justifyContent: 'center',
  },
  coloredButton: {
    backgroundColor: lmsStyle['base-primary'],
    color: 'white',
    width: 'fit-content',
    minWidth: '119px',
    height: '36px',
    fontSize: '13px',
    marginTop: '90px',
  },
  coloredButton1: {
    backgroundColor: lmsStyle['base-secondary'],
    color: 'white',
    width: '119px',
    height: '36px',
    marginLeft: '10px',
    fontSize: '13px',
    marginTop: '90px',
  },
  browseFileText: {
    color: 'blue',
    textDecoration: 'underline',
    cursor: 'pointer',
  },
  fileItem: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '55px',
    padding: '0 20px',
    fontSize: '10px',
    fontWeight: 'bold',
    border: '1px solid var(--base-gray-300)',
    borderRadius: '5px',
    boxShadow: '0px 3px 3px #00000008',
    color: '#16395b',
    '& > div > img': {
      height: '25px',
      marginRight: '10px',
    },
  },
}));
